export { default as Navbar } from './Navbar';
export { default as Header } from './Header.jsx';
export { default as About } from './About.jsx';
export { default as Footer } from './Footer.jsx'
export { default as Detail } from './Detail.jsx'
export { default as Services } from './Services.jsx'
export { default as Project } from './Project.jsx'
export { default as Contact } from './Contact.jsx'
export { default as Experience } from './Experience.jsx'
